source 'https://rubygems.org'

# Specify your gem's dependencies in busgogo.gemspec
gemspec

group :production do
 gem 'pg'
end
group :development, :test do
 gem 'sqlite3'
end

group :production do
  gem 'thin'
end


group :test do
  gem 'rake'

end
